---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.5
    - 1.6
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  install:
    - go get github.com/golang/lint/golint
  script:
    - go build hello/linkedlist.go
